---
language: python
services: docker

env:
  global:
    - ROLE_NAME: theo-agent
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

matrix:
  include:
    - os: osx
      language: generic

install:
  - pip install molecule[docker]

before_install:
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install python
      virtualenv venv -p python
      source venv/bin/activate
      pip install -q ansible
    fi

before_script:
  - cd ..
  - mv ansible-role-$ROLE_NAME ansible-$ROLE_NAME
  - cd ansible-$ROLE_NAME

script:
  - molecule --debug test
