---
language: python
services: docker

env:
  global:
    - ROLE_NAME: theo-agent
  matrix:
    - MOLECULE_DISTRO=centos6
    - MOLECULE_DISTRO=centos7

install:
  - pip install molecule[docker]

before_script:
  - cd ..
  - mv ansible-role-$ROLE_NAME ansible-$ROLE_NAME
  - cd ansible-$ROLE_NAME

script:
  - molecule --debug test --all

notifications:
  webhooks:
    urls: https://galaxy.ansible.com/api/v1/notifications/
    if: tag IS present
