---
- name: Set AuthorizedKeysCommandUser config snippet
  set_fact:
    sshd_authorized_keys_command_user_options:
      - regexp: "^AuthorizedKeysCommandUser"
        line: "AuthorizedKeysCommandUser {{ theo_agent_user }}"
  when: not ( ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6 )

- name: Set AuthorizedKeysCommandRunAs config snippet
  set_fact:
    sshd_authorized_keys_command_user_options:
      - regexp: "^AuthorizedKeysCommandRunAs"
        line: "AuthorizedKeysCommandRunAs {{ theo_agent_user }}"
  when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6 )

- name: Update sshd AuthorizedKeysCommand{User,RunAs} configuration options
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "/usr/sbin/sshd -T -f %s"
  with_items: "{{ sshd_authorized_keys_command_user_options }}"
  notify: Restart sshd

- name: Update remaining sshd configuration options
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "/usr/sbin/sshd -T -f %s"
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^AuthorizedKeysFile"
      line: "AuthorizedKeysFile {{ theo_agent_cache_dir }}/%u"
    - regexp: "^AuthorizedKeysCommand "
      line: "AuthorizedKeysCommand {{ theo_agent_path }} -config-file {{ theo_agent_config_path }} -cache-path {{ theo_agent_cache_dir }} %u"
  notify: Restart sshd
